version: "3"

services:
  api:
    container_name: yonks
    hostname: yonks
    build:
      context: .
      dockerfile: ./docker/api/api.Dockerfile
    ports:
      - ${APP_EXPOSE_PORT}:${APP_PORT}
    restart: always
    depends_on:
      - db

networks:
  default:
    name: yonks_network
